name: catatsaku_full
description: A Flutter app combining login and Catatsaku features.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  calendar_appbar: ^0.0.6
  intl: ^0.17.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.8.2
  icons_plus: ^4.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.1
  build_runner: ^2.4.15
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo.png
